repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.11.0
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        args: [--config=tox.ini]
        additional_dependencies: [flake8-isort==4.0.0, flake8-typing-imports==1.10.1, flake8-bugbear==21.4.3]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        args: [-n, '10', '--ini', 'tox.ini', '-x', 'tests']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-ast
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: check-merge-conflict
